import { CALLBACK } from "../config/constants";
import Captcha from "../packets/implementations/Captcha";
import CaptchaLocation from "../packets/implementations/CaptchaLocation";
import HideLoader from "../packets/implementations/HideLoader";
import InviteEnabled from "../packets/implementations/InviteEnabled";
import LoadDependencies from "../packets/implementations/LoadDependencies";
import Ping from "../packets/implementations/Ping";
import RecoveryEmailInvalidCode from "../packets/implementations/RecoveryEmailInvalidCode";
import Registration from "../packets/implementations/Registration";
import SocialNetwork from "../packets/implementations/SocialNetwork";
import { ProTankiClient } from "../server/ProTankiClient";
import { ProTankiServer } from "../server/ProTankiServer";
import { ResourceId } from "../types/resourceTypes";
import generateCaptcha from "../utils/GenerateCaptcha";
import logger from "../utils/Logger";
import { ResourceManager } from "../utils/ResourceManager";

export class LoginWorkflow {
  public static async sendLoginScreenData(client: ProTankiClient, server: ProTankiServer): Promise<void> {
    client.sendPacket(new Ping());
    client.sendPacket(new SocialNetwork(server.getSocialNetworks()));
    client.sendPacket(new CaptchaLocation(server.configService.getCaptchaLocations()));

    const resourceIds: ResourceId[] = [
      "ui/language_images",
      "ui/login_background",
      "ui/quests/icons/battle_score",
      "ui/quests/icons/get_crystal",
      "ui/quests/icons/kill_enemies",
      "ui/quests/window/week1/quest_chain",
      "ui/quests/window/week2/quest_chain",
      "ui/quests/window/week3/quest_chain",
      "ui/quests/window/week4/quest_chain",
      "ui/quests/window/week1/final_reward",
      "ui/quests/window/week2/final_reward",
      "ui/quests/window/week3/final_reward",
      "ui/quests/window/week4/final_reward",
      "sounds/notifications/battle_invite",
      "maps/map_zone/preview/SUMMER",
      "maps/map_zone/preview/WINTER",
      "maps/map_zone/preview/SPACE",
      "maps/map_kolhoz/preview/SUMMER",
      "maps/map_kolhoz/preview/WINTER",
      "maps/map_kolhoz/preview/SPACE",
      "maps/map_atra/preview/SUMMER",
      "maps/map_atra/preview/WINTER",
      "maps/map_atra/preview/SPACE",
      "maps/map_gravity/preview/SUMMER",
      "maps/map_gravity/preview/WINTER",
      "maps/map_gravity/preview/SPACE",
      "maps/map_sandbox/preview/SUMMER",
      "maps/map_sandbox/preview/WINTER",
      "maps/map_sandbox/preview/SUMMER_NIGHT",
      "maps/map_sandbox/preview/SPACE",
      "maps/map_garder/preview/SUMMER",
      "maps/map_garder/preview/WINTER",
      "maps/map_garder/preview/SPACE",
      "maps/map_beachfort/preview/SUMMER",
      "maps/map_skyscrapers/preview/SUMMER",
      "maps/map_skyscrapers/preview/SPACE",
      "maps/map_industrial_zone/preview/SUMMER",
      "maps/map_industrial_zone/preview/WINTER",
      "maps/map_industrial_zone/preview/SPACE",
      "maps/map_combe/preview/SUMMER",
      "maps/map_combe/preview/WINTER",
      "maps/map_combe/preview/SPACE",
      "maps/map_novel/preview/SUMMER",
      "maps/map_novel/preview/WINTER",
      "maps/map_novel/preview/SPACE",
      "maps/map_deathtrack/preview/SUMMER",
      "maps/map_deathtrack/preview/WINTER",
      "maps/map_deathtrack/preview/SPACE",
      "maps/map_montecarlo/preview/SUMMER",
      "maps/map_montecarlo/preview/WINTER",
      "maps/map_montecarlo/preview/SPACE",
      "maps/map_sandal/preview/SUMMER",
      "maps/map_sandal/preview/WINTER",
      "maps/map_sandal/preview/SPACE",
      "maps/map_dust2/preview/SUMMER",
      "maps/map_dust2/preview/SUMMER_NIGHT",
      "maps/map_dust2/preview/WINTER",
      "maps/map_dust2/preview/WINTER_NIGHT",
      "maps/map_camp/preview/SUMMER",
      "maps/map_camp/preview/WINTER",
      "maps/map_camp/preview/SPACE",
      "maps/map_fortknox/preview/SUMMER",
      "maps/map_fortknox/preview/WINTER",
      "maps/map_fortknox/preview/SPACE",
      "maps/map_trains/preview/SUMMER",
      "maps/map_trains/preview/WINTER",
      "maps/map_trains/preview/SPACE",
      "maps/map_event_relay/preview/SUMMER",
      "maps/map_event_relay/preview/SPACE",
      "maps/map_canyon/preview/SUMMER",
      "maps/map_canyon/preview/WINTER",
      "maps/map_canyon/preview/SPACE",
      "maps/map_ringnew/preview/SUMMER",
      "maps/map_ny_yorkshire/preview/WINTER_NIGHT",
      "maps/map_solikamsk/preview/SUMMER",
      "maps/map_solikamsk/preview/WINTER",
      "maps/map_solikamsk/preview/SPACE",
      "maps/map_legacy/preview/SUMMER",
      "maps/map_event_furyroad/preview/SUMMER",
      "maps/map_event_furyroad/preview/SPACE",
      "maps/map_Ice_v5/preview/WINTER_NIGHT",
      "maps/map_mop/preview/SUMMER",
      "maps/map_wave/preview/SUMMER",
      "maps/map_wave/preview/WINTER",
      "maps/map_wave/preview/SPACE",
      "maps/map_rio/preview/SUMMER",
      "maps/map_rio/preview/SUMMER_NIGHT",
      "maps/map_rio/preview/SPACE",
      "maps/map_ny_megahill/preview/WINTER_NIGHT",
      "maps/map_polygon/preview/SUMMER",
      "maps/map_polygon/preview/WINTER",
      "maps/map_polygon/preview/SUMMER_NIGHT",
      "maps/map_polygon/preview/SPACE",
      "maps/map_esplanade/preview/SUMMER",
      "maps/map_esplanade/preview/WINTER",
      "maps/map_esplanade/preview/SPACE",
      "maps/map_ny_trassa/preview/WINTER_NIGHT",
      "maps/map_minecraft/preview/SUMMER",
      "maps/map_event_headspinners/preview/SUMMER",
      "maps/map_event_headspinners/preview/SPACE",
      "maps/map_duel/preview/SUMMER",
      "maps/map_duel/preview/WINTER",
      "maps/map_duel/preview/SPACE",
      "maps/map_cologne/preview/SUMMER",
      "maps/map_baggage/preview/SUMMER",
      "maps/map_yorkshire_hell/preview/SUMMER",
      "maps/map_cross/preview/SUMMER",
      "maps/map_cross/preview/WINTER",
      "maps/map_cross/preview/SPACE",
      "maps/map_dusseldorf/preview/SUMMER",
      "maps/map_dusseldorf/preview/WINTER",
      "maps/map_dusseldorf/preview/SPACE",
      "maps/map_dualiti/preview/SUMMER",
      "maps/map_dualiti/preview/WINTER",
      "maps/map_dualiti/preview/SPACE",
      "maps/map_new_year_yorkshir/preview/WINTER",
      "maps/map_halloween/preview/SUMMER",
      "maps/map_gallery/preview/SUMMER",
      "maps/map_highway/preview/SUMMER",
      "maps/map_highway/preview/WINTER",
      "maps/map_highway/preview/SPACE",
      "maps/map_bridges/preview/SUMMER",
      "maps/map_bridges/preview/WINTER",
      "maps/map_bridges/preview/SPACE",
      "maps/map_serpuhov_gt/preview/SUMMER",
      "maps/map_magistral/preview/SUMMER",
      "maps/map_magistral/preview/WINTER",
      "maps/map_magistral/preview/SPACE",
      "maps/map_halloween_2023_dxxth/preview/SUMMER",
      "maps/map_brest/preview/SUMMER",
      "maps/map_brest/preview/WINTER",
      "maps/map_brest/preview/SPACE",
      "maps/map_ny_snowarena/preview/WINTER_NIGHT",
      "maps/map_highland/preview/SUMMER",
      "maps/map_highland/preview/WINTER",
      "maps/map_highland/preview/SPACE",
      "maps/map_platform/preview/SPACE",
      "maps/map_ny_Castle/preview/WINTER_NIGHT",
      "maps/map_gubakha/preview/SUMMER",
      "maps/map_gubakha/preview/WINTER",
      "maps/map_gubakha/preview/SPACE",
      "maps/map_osa/preview/SUMMER",
      "maps/map_osa/preview/WINTER",
      "maps/map_osa/preview/SPACE",
      "maps/map_scope/preview/SUMMER",
      "maps/map_scope/preview/WINTER",
      "maps/map_scope/preview/SPACE",
      "maps/map_island/preview/SUMMER",
      "maps/map_island/preview/WINTER",
      "maps/map_island/preview/SPACE",
      "maps/map_stadium/preview/SUMMER",
      "maps/map_stadium/preview/WINTER",
      "maps/map_stadium/preview/SUMMER_NIGHT",
      "maps/map_stadium/preview/SPACE",
      "maps/map_ny_island/preview/WINTER_NIGHT",
      "maps/map_polygon_gt/preview/SUMMER",
      "maps/map_boombox/preview/SUMMER",
      "maps/map_boombox/preview/WINTER",
      "maps/map_boombox/preview/SPACE",
      "maps/map_ny_snowbattle/preview/WINTER_NIGHT",
      "maps/map_Ice_v5_2/preview/WINTER",
      "maps/map_ny_john/preview/WINTER_NIGHT",
      "maps/map_magadan/preview/SUMMER",
      "maps/map_magadan/preview/WINTER",
      "maps/map_magadan/preview/SPACE",
      "maps/map_event_sumo/preview/SUMMER",
      "maps/map_event_sumo/preview/SPACE",
      "maps/map_cosmicstation/preview/SPACE",
      "maps/map_siege/preview/SUMMER",
      "maps/map_siege/preview/WINTER",
      "maps/map_siege/preview/SPACE",
      "maps/map_shortbridge/preview/SUMMER",
      "maps/map_shortbridge/preview/WINTER",
      "maps/map_shortbridge/preview/SPACE",
      "maps/map_farm/preview/SUMMER",
      "maps/map_farm/preview/WINTER",
      "maps/map_farm/preview/SPACE",
      "maps/map_chornobyl/preview/SUMMER",
      "maps/map_chornobyl/preview/WINTER",
      "maps/map_chornobyl/preview/SPACE",
      "maps/map_kungur/preview/SUMMER",
      "maps/map_kungur/preview/WINTER",
      "maps/map_kungur/preview/SPACE",
      "maps/map_moon/preview/SPACE",
      "maps/map_valley/preview/SUMMER",
      "maps/map_valley/preview/WINTER",
      "maps/map_valley/preview/SPACE",
      "maps/map_skirmish/preview/SUMMER",
      "maps/map_skirmish/preview/SUMMER_NIGHT",
      "maps/map_skirmish/preview/SPACE",
      "maps/map_ny_aleksandrovsk/preview/WINTER_NIGHT",
      "maps/map_halloween_2023_errorcg/preview/SUMMER",
      "maps/map_2042/preview/SUMMER",
      "maps/map_2042/preview/WINTER",
      "maps/map_2042/preview/SPACE",
      "maps/map_ny_boombox/preview/WINTER_NIGHT",
      "maps/map_arena/preview/SUMMER",
      "maps/map_arena/preview/WINTER",
      "maps/map_arena/preview/SPACE",
      "maps/map_pingpong/preview/SUMMER",
      "maps/map_pingpong/preview/WINTER",
      "maps/map_pingpong/preview/SPACE",
      "maps/map_losttemple/preview/SUMMER",
      "maps/map_losttemple/preview/WINTER",
      "maps/map_losttemple/preview/SPACE",
      "maps/map_factory/preview/SUMMER",
      "maps/map_factory/preview/SPACE",
      "maps/map_iran/preview/SUMMER",
      "maps/map_iran/preview/WINTER",
      "maps/map_iran/preview/SUMMER_NIGHT",
      "maps/map_iran/preview/WINTER_NIGHT",
      "maps/map_iran/preview/SPACE",
      "maps/map_courage/preview/SUMMER",
      "maps/map_courage/preview/WINTER",
      "maps/map_courage/preview/SPACE",
      "maps/map_pass/preview/SUMMER",
      "maps/map_pass/preview/WINTER",
      "maps/map_pass/preview/SPACE",
      "maps/map_skylark/preview/SUMMER",
      "maps/map_skylark/preview/WINTER",
      "maps/map_skylark/preview/SPACE",
      "maps/map_berlin/preview/SUMMER",
      "maps/map_berlin/preview/WINTER",
      "maps/map_berlin/preview/SPACE",
      "maps/map_cologne_hell/preview/SUMMER",
      "maps/map_desert/preview/SUMMER",
      "maps/map_desert/preview/WINTER",
      "maps/map_desert/preview/SPACE",
      "maps/map_tribute/preview/SUMMER",
      "maps/map_tribute/preview/WINTER",
      "maps/map_tribute/preview/SPACE",
      "maps/map_opposition/preview/SUMMER",
      "maps/map_opposition/preview/WINTER",
      "maps/map_opposition/preview/SPACE",
      "maps/map_wolfenstein/preview/SUMMER",
      "maps/map_wolfenstein/preview/WINTER",
      "maps/map_wolfenstein/preview/SPACE",
      "maps/map_lab/preview/SPACE",
      "maps/map_madness_space/preview/SPACE",
      "maps/map_silence/preview/SUMMER",
      "maps/map_silence/preview/WINTER",
      "maps/map_silence/preview/SUMMER_NIGHT",
      "maps/map_silence/preview/SPACE",
      "maps/map_madness_old/preview/SPACE",
      "maps/map_future/preview/SUMMER",
      "maps/map_future/preview/SUMMER_NIGHT",
      "maps/map_future/preview/SPACE",
      "maps/map_aleksandrovsk/preview/SUMMER",
      "maps/map_aleksandrovsk/preview/WINTER",
      "maps/map_aleksandrovsk/preview/SUMMER_NIGHT",
      "maps/map_aleksandrovsk/preview/SPACE",
      "maps/map_bobruisk/preview/SUMMER",
      "maps/map_bobruisk/preview/WINTER",
      "maps/map_bobruisk/preview/SPACE",
      "maps/map_highland_gt/preview/SUMMER",
      "maps/map_massacre/preview/SUMMER",
      "maps/map_massacre/preview/WINTER",
      "maps/map_massacre/preview/SPACE",
      "maps/map_hill/preview/SUMMER",
      "maps/map_hill/preview/WINTER",
      "maps/map_hill/preview/SPACE",
      "maps/map_rift/preview/SUMMER",
      "maps/map_rift/preview/WINTER",
      "maps/map_rift/preview/SPACE",
      "maps/map_edinburgh/preview/SUMMER",
      "maps/map_edinburgh/preview/WINTER",
      "maps/map_edinburgh/preview/SPACE",
      "maps/map_abyss/preview/SUMMER",
      "maps/map_abyss/preview/WINTER",
      "maps/map_abyss/preview/SPACE",
      "maps/map_forest/preview/SUMMER",
      "maps/map_forest/preview/WINTER",
      "maps/map_forest/preview/SPACE",
      "maps/map_silence_gt/preview/SUMMER",
      "maps/map_springfalls/preview/SUMMER",
      "maps/map_silence_moon/preview/SPACE",
      "maps/map_hayro_crazyrace/preview/SUMMER",
      "maps/map_deck9/preview/SUMMER",
      "maps/map_deck9/preview/WINTER",
      "maps/map_deck9/preview/SPACE",
      "maps/map_parma/preview/SUMMER",
      "maps/map_parma/preview/WINTER",
      "maps/map_parma/preview/SPACE",
      "maps/map_subway/preview/SUMMER",
      "maps/map_subway/preview/WINTER",
      "maps/map_subway/preview/SPACE",
      "maps/map_station/preview/SUMMER",
      "maps/map_station/preview/WINTER",
      "maps/map_station/preview/SPACE",
      "maps/map_barda/preview/SUMMER",
      "maps/map_barda/preview/WINTER",
      "maps/map_barda/preview/SUMMER_NIGHT",
      "maps/map_barda/preview/SPACE",
      "maps/map_redalert/preview/SUMMER",
      "maps/map_redalert/preview/WINTER",
      "maps/map_redalert/preview/SPACE",
      "maps/map_crash/preview/SUMMER",
      "maps/map_molotov/preview/SUMMER",
      "maps/map_molotov/preview/WINTER",
      "maps/map_molotov/preview/SPACE",
      "maps/map_serpuhov/preview/SUMMER",
      "maps/map_serpuhov/preview/WINTER",
      "maps/map_serpuhov/preview/SPACE",
      "maps/map_noise/preview/SUMMER",
      "maps/map_noise/preview/WINTER",
      "maps/map_noise/preview/SPACE",
      "maps/map_battlecity/preview/SUMMER",
      "bonuses/nitro",
      "bonuses/damage",
      "bonuses/armor",
      "bonuses/health",
      "bonuses/crystal",
      "bonuses/gold",
      "bonuses/special",
      "bonuses/moon",
      "bonuses/pumpkin",
      "bonuses/parachute/cord",
      "bonuses/parachute/inner",
      "bonuses/parachute/main",
      "sounds/bonus_pickup",
    ];

    const dependencies = {
      resources: ResourceManager.getBulkResources(resourceIds),
    };
    client.sendPacket(new LoadDependencies(dependencies, CALLBACK.LOGIN_FORM));
  }

  public static initializeLoginForm(client: ProTankiClient, server: ProTankiServer): void {
    client.sendPacket(new InviteEnabled(server.getNeedInviteCode()));

    const loginForm = server.getLoginForm();
    client.sendPacket(new Registration(loginForm.bgResource, loginForm.enableRequiredEmail, loginForm.maxPasswordLength, loginForm.minPasswordLength));

    client.sendPacket(new HideLoader());
  }

  public static handleInvalidRecoveryCode(client: ProTankiClient): void {
    const captcha = generateCaptcha();
    client.captchaSolution = captcha.text;

    client.sendPacket(new RecoveryEmailInvalidCode());
    client.sendPacket(new Captcha(3, captcha.image));
  }
}
