export const battleDetailsData: { [key: string]: any } = {
  "66b5174747d555fb": {
    battleMode: "CTF",
    itemId: "66b5174747d555fb",
    scoreLimit: 7,
    timeLimitInSec: 0,
    mapId: "map_sandbox",
    maxPeopleCount: 4,
    name: "Sandbox CTF",
    proBattle: true,
    minRank: 23,
    maxRank: 30,
    roundStarted: true,
    spectator: false,
    withoutBonuses: true,
    withoutCrystals: false,
    withoutSupplies: true,
    proBattleEnterPrice: 150,
    timeLeftInSec: -1750909108,
    userPaidNoSuppliesBattle: true,
    proBattleTimeLeftInSec: 1,
    parkourMode: false,
    equipmentConstraintsMode: "HORNET_WASP_RAILGUN",
    reArmorEnabled: false,
    reducedResistance: false,
    esportDropTiming: false,
    withoutGoldBoxes: false,
    withoutGoldSiren: false,
    withoutGoldZone: true,
    withoutMedkit: false,
    withoutMines: false,
    randomGold: true,
    dependentCooldownEnabled: false,
    usersBlue: [
      { kills: 11, score: 161, suspicious: false, user: "BepTyxau" },
      { kills: 10, score: 122, suspicious: false, user: "infront" },
      { kills: 6, score: 225, suspicious: false, user: "Ferxxo" },
      { kills: 14, score: 108, suspicious: false, user: "blacknoir" },
    ],
    usersRed: [
      { kills: 7, score: 174, suspicious: false, user: "Mohammedx" },
      { kills: 5, score: 156, suspicious: false, user: "El_Retorno2.0" },
      { kills: 7, score: 62, suspicious: false, user: "Wskelly" },
      { kills: 9, score: 115, suspicious: false, user: "nozzey" },
    ],
    scoreRed: 1,
    scoreBlue: 2,
    autoBalance: false,
    friendlyFire: false,
  },
};
