export const ENCRYPTION_CONSTANTS = {
  KEY_LENGTH: 8,
  DECRYPT_XOR_VALUE: 87,
  POSITION_MASK: 7,
};

export const INVITE_CODE_LENGTH = 5;
export const INVITE_CODE_CHARACTERS = "0123456789abcdef";

export const DEFAULT_PORT = 1337;
export const DEFAULT_MAX_CLIENTS = 10;

export const CALLBACK = {
  LOGIN_FORM: 3,
  GARAGE_DATA: 4,
  LOBBY_DATA: 5,
  BATTLE_MAP_LIBS_LOADED: 6,
};
