import { ResourceManager } from "../utils/ResourceManager";

export const getGarageItemsData = () => ({
  items: [
    {
      id: "smoky",
      name: "Canhão-fumegante",
      description: "Texto do Smoky",
      isInventory: false,
      index: 100,
      next_price: 166900,
      next_rank: 23,
      type: 1,
      baseItemId: 651066,
      previewResourceId: ResourceManager.getIdlowById("turret/smoky/m3/preview"),
      rank: 23,
      category: "weapon",
      properts: [
        {
          property: "DAMAGE",
          value: null,
          subproperties: [
            { property: "DAMAGE_FROM", value: "44", subproperties: null },
            { property: "DAMAGE_TO", value: "56", subproperties: null },
          ],
        },
        { property: "IMPACT_FORCE", value: "330", subproperties: null },
        { property: "TURRET_TURN_SPEED", value: "122.6", subproperties: null },
        { property: "CRITICAL_HIT_CHANCE", value: "20", subproperties: null },
        { property: "CRITICAL_HIT_DAMAGE", value: "100", subproperties: null },
      ],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 166900,
      remainingTimeInSec: -1,
      modificationID: 3,
      object3ds: ResourceManager.getIdlowById("turret/smoky/m3/model"),
    },
    {
      id: "wasp",
      name: "Vespa",
      description: "Texto do Wasp",
      isInventory: false,
      index: 700,
      next_price: 172600,
      next_rank: 24,
      type: 2,
      baseItemId: 629496,
      previewResourceId: ResourceManager.getIdlowById("hull/wasp/m3/preview"),
      rank: 24,
      category: "armor",
      properts: [
        { property: "HULL_ARMOR", value: "180", subproperties: null },
        { property: "HULL_SPEED", value: "13.00", subproperties: null },
        { property: "HULL_TURN_SPEED", value: "150", subproperties: null },
        { property: "HULL_MASS", value: "2200", subproperties: null },
        { property: "HULL_POWER", value: null, subproperties: [{ property: "HULL_ACCELERATION", value: "13", subproperties: null }] },
      ],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 172600,
      remainingTimeInSec: -1,
      modificationID: 3,
      object3ds: ResourceManager.getIdlowById("hull/wasp/m3/model"),
    },
    {
      id: "green",
      name: "Verde",
      description: "Example",
      isInventory: false,
      index: 1100,
      next_price: 0,
      next_rank: 1,
      type: 3,
      baseItemId: ResourceManager.getIdlowById("paint/green/preview"),
      previewResourceId: ResourceManager.getIdlowById("paint/green/preview"),
      rank: 1,
      category: "paint",
      properts: [],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 0,
      remainingTimeInSec: -1,
      coloring: ResourceManager.getIdlowById("paint/green/texture"),
    },
    {
      id: "holiday",
      name: "Feriado",
      description: "Example",
      isInventory: false,
      index: 1200,
      next_price: 0,
      next_rank: 1,
      type: 3,
      baseItemId: ResourceManager.getIdlowById("paint/holiday/preview"),
      previewResourceId: ResourceManager.getIdlowById("paint/holiday/preview"),
      rank: 1,
      category: "paint",
      properts: [],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 0,
      remainingTimeInSec: -1,
      coloring: ResourceManager.getIdlowById("paint/holiday/texture"),
    },
  ],
  garageBoxId: ResourceManager.getIdlowById("garage"),
});

export const getShopItemsData = () => ({
  items: [
    {
      id: "smoky",
      name: "Canhão-fumegante",
      description: "Texto do Smoky",
      isInventory: false,
      index: 100,
      next_price: 7100,
      next_rank: 8,
      type: 1,
      baseItemId: 651066,
      previewResourceId: ResourceManager.getIdlowById("turret/smoky/m0/preview"),
      rank: 1,
      category: "weapon",
      properts: [
        {
          property: "DAMAGE",
          value: null,
          subproperties: [
            { property: "DAMAGE_FROM", value: "22", subproperties: null },
            { property: "DAMAGE_TO", value: "28", subproperties: null },
          ],
        },
        { property: "IMPACT_FORCE", value: "175", subproperties: null },
        { property: "TURRET_TURN_SPEED", value: "71.5", subproperties: null },
        { property: "CRITICAL_HIT_CHANCE", value: "8", subproperties: null },
        { property: "CRITICAL_HIT_DAMAGE", value: "50", subproperties: null },
      ],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 0,
      remainingTimeInSec: -1,
      modificationID: 0,
      object3ds: ResourceManager.getIdlowById("turret/smoky/m0/model"),
    },
    {
      id: "smoky",
      name: "Canhão-fumegante",
      description: "Texto do Smoky",
      isInventory: false,
      index: 100,
      next_price: 61400,
      next_rank: 15,
      type: 1,
      baseItemId: 651066,
      previewResourceId: ResourceManager.getIdlowById("turret/smoky/m1/preview"),
      rank: 8,
      category: "weapon",
      properts: [
        {
          property: "DAMAGE",
          value: null,
          subproperties: [
            { property: "DAMAGE_FROM", value: "29", subproperties: null },
            { property: "DAMAGE_TO", value: "37", subproperties: null },
          ],
        },
        { property: "IMPACT_FORCE", value: "222", subproperties: null },
        { property: "TURRET_TURN_SPEED", value: "87.1", subproperties: null },
        { property: "CRITICAL_HIT_CHANCE", value: "12", subproperties: null },
        { property: "CRITICAL_HIT_DAMAGE", value: "65", subproperties: null },
      ],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 7100,
      remainingTimeInSec: -1,
      modificationID: 1,
      object3ds: ResourceManager.getIdlowById("turret/smoky/m1/model"),
    },
    {
      id: "smoky",
      name: "Canhão-fumegante",
      description: "Texto do Smoky",
      isInventory: false,
      index: 100,
      next_price: 166900,
      next_rank: 23,
      type: 1,
      baseItemId: 651066,
      previewResourceId: ResourceManager.getIdlowById("turret/smoky/m2/preview"),
      rank: 15,
      category: "weapon",
      properts: [
        {
          property: "DAMAGE",
          value: null,
          subproperties: [
            { property: "DAMAGE_FROM", value: "35", subproperties: null },
            { property: "DAMAGE_TO", value: "45", subproperties: null },
          ],
        },
        { property: "IMPACT_FORCE", value: "269", subproperties: null },
        { property: "TURRET_TURN_SPEED", value: "102.6", subproperties: null },
        { property: "CRITICAL_HIT_CHANCE", value: "15", subproperties: null },
        { property: "CRITICAL_HIT_DAMAGE", value: "80", subproperties: null },
      ],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 61400,
      remainingTimeInSec: -1,
      modificationID: 2,
      object3ds: ResourceManager.getIdlowById("turret/smoky/m2/model"),
    },
    {
      id: "wasp",
      name: "Vespa",
      description: "Texto do Wasp",
      isInventory: false,
      index: 700,
      next_price: 7650,
      next_rank: 9,
      type: 2,
      baseItemId: 629496,
      previewResourceId: ResourceManager.getIdlowById("hull/wasp/m0/preview"),
      rank: 2,
      category: "armor",
      properts: [
        { property: "HULL_ARMOR", value: "94", subproperties: null },
        { property: "HULL_SPEED", value: "10.80", subproperties: null },
        { property: "HULL_TURN_SPEED", value: "93.9", subproperties: null },
        { property: "HULL_MASS", value: "1376", subproperties: null },
        { property: "HULL_POWER", value: null, subproperties: [{ property: "HULL_ACCELERATION", value: "9.4", subproperties: null }] },
      ],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 200,
      remainingTimeInSec: -1,
      modificationID: 0,
      object3ds: ResourceManager.getIdlowById("hull/wasp/m0/model"),
    },
    {
      id: "wasp",
      name: "Vespa",
      description: "Texto do Wasp",
      isInventory: false,
      index: 700,
      next_price: 62450,
      next_rank: 16,
      type: 2,
      baseItemId: 629496,
      previewResourceId: ResourceManager.getIdlowById("hull/wasp/m1/preview"),
      rank: 9,
      category: "armor",
      properts: [
        { property: "HULL_ARMOR", value: "121", subproperties: null },
        { property: "HULL_SPEED", value: "11.50", subproperties: null },
        { property: "HULL_TURN_SPEED", value: "111.7", subproperties: null },
        { property: "HULL_MASS", value: "1638", subproperties: null },
        { property: "HULL_POWER", value: null, subproperties: [{ property: "HULL_ACCELERATION", value: "10.6", subproperties: null }] },
      ],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 7650,
      remainingTimeInSec: -1,
      modificationID: 1,
      object3ds: ResourceManager.getIdlowById("hull/wasp/m1/model"),
    },
    {
      id: "wasp",
      name: "Vespa",
      description: "Texto do Wasp",
      isInventory: false,
      index: 700,
      next_price: 172600,
      next_rank: 24,
      type: 2,
      baseItemId: 629496,
      previewResourceId: ResourceManager.getIdlowById("hull/wasp/m2/preview"),
      rank: 16,
      category: "armor",
      properts: [
        { property: "HULL_ARMOR", value: "149", subproperties: null },
        { property: "HULL_SPEED", value: "12.20", subproperties: null },
        { property: "HULL_TURN_SPEED", value: "129.6", subproperties: null },
        { property: "HULL_MASS", value: "1901", subproperties: null },
        { property: "HULL_POWER", value: null, subproperties: [{ property: "HULL_ACCELERATION", value: "11.7", subproperties: null }] },
      ],
      discount: { percent: 0, timeLeftInSeconds: -1751196680, timeToStartInSeconds: -1751196680 },
      grouped: false,
      isForRent: false,
      price: 62450,
      remainingTimeInSec: -1,
      modificationID: 2,
      object3ds: ResourceManager.getIdlowById("hull/wasp/m2/model"),
    },
  ],
  delayMountArmorInSec: 0,
  delayMountWeaponInSec: 0,
  delayMountColorInSec: 0,
});
